### ISSUE TITLE
Fill in README

### ISSUE THREAD

**Issue by tomekowal** [half-t/zmq_ex#4]
Hey guys! I want to participate a little bit, but I am not sure what is the end goal.
Could you explain what the project goal is?
How is it going to be different from existing work https://hex.pm/packages?_utf8=%E2%9C%93&search=zeromq&sort=recent_downloads

Is the project goal to learn or to make something production ready?

In case you'd like to make it production ready, I suggest using connection library for permanent connections https://hex.pm/packages/connection
And ranch as TCP acceptor pool https://hex.pm/packages/ranch
It would make both currently open PRs unnecessary.
(I am not that familiar with ZeroMQ so please check if that makes sense)

**Comment by fabiankrol** [comment]
@tomekowal It's purely a learning project. There is no plan to make it production ready in near future. 

We're going to starts slow with custom implementation for everything. We'll add dedicated libraries when we get (and understand) issues they're solving ;)

cc @Dreat @nenros

**Comment by fabiankrol** [comment]
@Dreat 

![](https://media.giphy.com/media/3oFyD2RpK1Qs4Cl9rq/giphy.gif)
